version: "3.9"

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: containers/db/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - weather_app_back_app_db
  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/api/Dockerfile
    env_file:
      - .env
    volumes:
      - ./application:/code/
      - ./static:/static
    ports:
      - "8000:8000"
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - weather_app_back_app_web
      - weather_app_back_app_db
  nginx:
    container_name: web
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    volumes:
      - ./static:/static
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - weather_app_back_app_web

volumes:
  db_data:
  static:


networks:
  weather_app_back_app_web:
  weather_app_back_app_db:
